# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- main

resources:
 repositories:
   - repository: github_repo_devops
     type: github
     endpoint: "Gitops Connection"
     name: MoOyeg/azure-dev-ops-with-managed-openshift-gitops

pool:
  name: AzurePipeline

variables:
  GIT_SHA: $(Build.SourceVersion)
  GIT_BRANCH: $(Build.SourceBranchName)
  ref: $[ resources.repositories.github_repo_devops.ref ]
  name: $[ resources.repositories.github_repo_devops.name ]
  id: $[ resources.repositories.github_repo_devops.id ]
  type: $[ resources.repositories.github_repo_devops.type ]
  url: $[ resources.repositories.github_repo_devops.url ]
  version: $[ resources.repositories.github_repo_devops.version ]

stages:
  - stage: CI
    displayName: CI Stage
    jobs:
      - job: build
        displayName: build
        steps:
        - task: CmdLine@2
          inputs:
            script: ls $(Build.SourcesDirectory)            
        - task: Docker@2.240.3
          displayName: Build and Push
          inputs:
            containerRegistry: 'container-registry-connection'
            repository: 'github_repo_devops'
            command: 'build'
            Dockerfile: $(Build.SourcesDirectory)/react-app-example/app/Dockerfile
            tags: $(GIT_SHA)
      - job: deploy
        displayName: Update Gitops Repo
        steps:        
          - checkout: github_repo_devops
            displayName: Checkout Gitops Repository
            persistCredentials: true
          - task: Bash@3
            displayName: Update image SHA signature
            inputs:
              targetType: inline
              script: |
                echo ${url}
                app_line_number=$(grep -n "name: test" $(Build.SourcesDirectory)/react-app-example/manifests/prod/kustomization.yaml | cut -d ":" -f1)
                if [ -z "$app_line_number" ]; then
                  echo "Will not replace the image in the kustomization.yaml file"
                else
                    image_line_number=$((app_line_number + 1))
                    sed -i "${image_line_number}s,.*,   newName: ${image}," $(Build.SourcesDirectory)/react-app-example/manifests/prod/kustomization.yaml
                    if [ $? -ne 0 ]; then
                        echo "Error in replacing the image in the kustomization.yaml file"
                    else
                        echo "Image replaced in the Devkustomization.yaml file"
                        image_tage_line_number=$((app_line_number + 2))
                        sed -i "${image_tage_line_number}s,.*,   newTag: $image_tag," /root/repos/azure-dev-ops-with-managed-openshift-gitops/react-app-example/manifests/prod/kustomization.yaml
                        echo "Image Tag replaced in the Prod kustomization.yaml file"        
                    fi
                fi


